#!/bin/bash
#
#  hostingsubapp    Startup script for the hosting submission application#
#
# chkconfig: 2345 75 25
# description: hostingsubapp
# processname: hostingsubapp
# Source function library.


### BEGIN vars
APP=hostingsubapp
APPNAME=dspacesubapp
PORT=9020
BASE_DIR=/opt/play-apps
PLAY_VERSION=23
APPLICATION_PATH=${BASE_DIR}/${PLAY_VERSION}/${APP}
PROD_PATH="${APPLICATION_PATH}/target/universal/stage"
CONF_PATH="${PROD_PATH}/conf/prod.conf"
USER=ottk




# Specific project configuration environment :
export _JAVA_OPTIONS="-Xms1024m -Xmx1024m"
### END vars

# Exit immediately if a command exits with a nonzero exit status.
set -e
echo "Updating"

    cd $APPLICATION_PATH || exit

    unset GIT_DIR
    # Update repo
    git pull

    cd $APPLICATION_PATH
    # Creating new project (MUST BE ON THE GOOD DIR)
    $APPLICATION_PATH/activator clean compile stage

exit 0
